apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomall-redis
  labels:
    app: gomall-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gomall-redis
  template:
    metadata:
      labels:
        app: gomall-redis
    spec:
      containers:
      - name: redis
        image: redis:7.0-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"