apiVersion: v1
kind: Service
metadata:
  name: gomall-redis
  labels:
    app: gomall-redis
spec:
  type: NodePort
  selector:
    app: gomall-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 31637