apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
data:
  conf.yaml: |
    kitex:
      service: "{{ .Values.services.cart.name }}"
      address: ":{{ .Values.services.cart.port }}"
      metrics_port: ":{{ .Values.services.cart.metricsPort }}"
      log_level: {{ .Values.services.cart.logConfig.level | quote }}
      log_file_name: {{ .Values.services.cart.logConfig.fileName | quote }}
      log_max_size: {{ .Values.services.cart.logConfig.maxSize }}
      log_max_age: {{ .Values.services.cart.logConfig.maxAge }}
      log_max_backups: {{ .Values.services.cart.logConfig.backups }}

    mysql:
      dsn: "%s:%s@tcp(%s:%d)/%s?charset=utf8mb4&parseTime=True&loc=Local"
      address: {{ .Values.mysql.address | quote }}  # 关键修复点
      port: {{ .Values.mysql.port }}
      username: {{ .Values.mysql.username | quote }}
      password: {{ .Values.mysql.password | quote }}
      database: {{ .Values.mysql.database | quote }}
      
    rate_limiter:
      enabled: {{ .Values.services.cart.rateLimiter.enabled }}
      bucket_size: {{ .Values.services.cart.rateLimiter.bucket_size }}
      rate: {{ .Values.services.cart.rateLimiter.rate }}