# checkout-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
spec:
  replicas: {{ .Values.services.checkout.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
      - name: checkout
        image: {{ .Values.services.checkout.image.repository | default "huajuan6848/checkout" }}:{{ .Values.services.checkout.image.tag | default "lab2" }}
        ports:
        - containerPort: {{ .Values.services.checkout.port | default 8884 }}  # 与 ConfigMap 端口联动
        volumeMounts:
        - name: config
          mountPath: /app/conf/dev
      volumes:
      - name: config
        configMap:
          name: {{ .Values.configMaps.checkout | default "checkout-config" }}