# order-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.order | default "order-config" }}
data:
  conf.yaml: |
    kitex:
      service: "{{ .Values.services.order.name | default "order" }}"
      address: ":{{ .Values.services.order.port | default 8885 }}"
      metrics_port: ":{{ .Values.services.order.metricsPort | default 9995 }}"
      log_level: "{{ .Values.services.order.logConfig.level | default "info" }}"
      log_file_name: "{{ .Values.services.order.logConfig.fileName | default "log/kitex.log" }}"
      log_max_size: {{ .Values.services.order.logConfig.maxSize | default 10 }}
      log_max_age: {{ .Values.services.order.logConfig.maxAge | default 3 }}
      log_max_backups: {{ .Values.services.order.logConfig.backups | default 50 }}

    mysql:
      dsn: "{{ .Values.mysql.dsn | default (printf "%s:%s@tcp(%s:%d)/%s?charset=utf8mb4&parseTime=True&loc=Local" .Values.mysql.username .Values.mysql.password .Values.mysql.address .Values.mysql.port .Values.services.order.database) }}"
      address: "{{ .Values.mysql.address | default "gomall-mysql" }}"
      port: {{ .Values.mysql.port | default 3306 }}
      username: "{{ .Values.mysql.username | default "root" }}"
      password: "{{ .Values.mysql.password | default "root" }}"
      database: "{{ .Values.services.order.database | default "order" }}"  # 服务独立数据库

    redis:
      address: "{{ .Values.redis.address | default "gomall-redis:6379" }}"
      username: "{{ .Values.redis.username | default "" }}"
      password: "{{ .Values.redis.password | default "" }}"
      db: {{ .Values.redis.db | default 0 }}
      
    rate_limiter:
      enabled: {{ .Values.services.order.rateLimiter.enabled | default true }}
      bucket_size: {{ .Values.services.order.rateLimiter.bucketSize | default 10 }}
      rate: {{ .Values.services.order.rateLimiter.rate | default 4 }}  # 独立限流配置