# order-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: {{ .Values.services.order.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: {{ .Values.services.order.image.repository | default "huajuan6848/order" }}:{{ .Values.services.order.image.tag | default "lab2" }}
        ports:
        - containerPort: {{ .Values.services.order.port | default 8885 }}  # 与 ConfigMap 严格对齐
        volumeMounts:
        - name: config
          mountPath: /app/conf/dev
      volumes:
      - name: config
        configMap:
          name: {{ .Values.configMaps.order | default "order-config" }}