# payment-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.payment | default "payment-config" }}
data:
  conf.yaml: |
    kitex:
      service: "{{ .Values.services.payment.name | default "payment" }}"
      address: ":{{ .Values.services.payment.port | default 8886 }}"
      metrics_port: ":{{ .Values.services.payment.metricsPort | default 9996 }}"
      log_level: "{{ .Values.services.payment.logConfig.level | default "info" }}"
      log_file_name: "{{ .Values.services.payment.logConfig.fileName | default "log/kitex.log" }}"
      log_max_size: {{ .Values.services.payment.logConfig.maxSize | default 10 }}
      log_max_age: {{ .Values.services.payment.logConfig.maxAge | default 3 }}
      log_max_backups: {{ .Values.services.payment.logConfig.backups | default 50 }}
      
    mysql:
      dsn: "%s:%s@tcp(%s:%d)/%s?charset=utf8mb4&parseTime=True&loc=Local"
      address: {{ .Values.mysql.address | quote }}
      port: {{ .Values.mysql.port }}
      username: {{ .Values.mysql.username | quote }}
      password: {{ .Values.mysql.password | quote }}
      database: {{ .Values.services.payment.database | quote }}  # 服务独立数据库

    rate_limiter:
      enabled: {{ .Values.services.payment.rateLimiter.enabled | default true }}
      bucket_size: {{ .Values.services.payment.rateLimiter.bucketSize | default 10 }}
      rate: {{ .Values.services.payment.rateLimiter.rate | default 3 }}  # 独立限流值