# product-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.product | default "product-config" }}
data:
  conf.yaml: |
    kitex:
      service: "{{ .Values.services.product.name | default "product" }}"
      address: ":{{ .Values.services.product.port | default 8881 }}"
      metrics_port: ":{{ .Values.services.product.metricsPort | default 9991 }}"
      log_level: "{{ .Values.services.product.logConfig.level | default "info" }}"
      log_file_name: "{{ .Values.services.product.logConfig.fileName | default "log/kitex.log" }}"
      log_max_size: {{ .Values.services.product.logConfig.maxSize | default 10 }}
      log_max_age: {{ .Values.services.product.logConfig.maxAge | default 3 }}
      log_max_backups: {{ .Values.services.product.logConfig.backups | default 50 }}

    mysql:
      dsn: "%s:%s@tcp(%s:%d)/%s?charset=utf8mb4&parseTime=True&loc=Local"
      address: {{ .Values.mysql.address | quote }}
      port: {{ .Values.mysql.port }}
      username: {{ .Values.mysql.username | quote }}
      password: {{ .Values.mysql.password | quote }}
      database: {{ .Values.services.product.database | quote }}  # 服务独立数据库

    redis:
      address: "{{ .Values.redis.address | default "gomall-redis:6379" }}"
      username: "{{ .Values.redis.username | default "" }}"
      password: "{{ .Values.redis.password | default "" }}"
      db: {{ .Values.redis.db | default 0 }}

    rate_limiter:
      enabled: {{ .Values.services.product.rateLimiter.enabled | default true }}
      bucket_size: {{ .Values.services.product.rateLimiter.bucketSize | default 10 }}
      rate: {{ .Values.services.product.rateLimiter.rate | default 10 }}  # 独立限流配置