# user-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.user | default "user-config" }}
data:
  conf.yaml: |
    kitex:
      service: "{{ .Values.services.user.name | default "user" }}"
      address: ":{{ .Values.services.user.port | default 8882 }}"
      metrics_port: ":{{ .Values.services.user.metricsPort | default 9992 }}"
      log_level: "{{ .Values.services.user.logConfig.level | default "debug" }}"
      log_file_name: "{{ .Values.services.user.logConfig.fileName | default "log/kitex.log" }}"
      log_max_size: {{ .Values.services.user.logConfig.maxSize | default 10 }}
      log_max_age: {{ .Values.services.user.logConfig.maxAge | default 3 }}
      log_max_backups: {{ .Values.services.user.logConfig.backups | default 50 }}
      
    mysql:
      dsn: "%s:%s@tcp(%s:%d)/%s?charset=utf8mb4&parseTime=True&loc=Local"
      address: {{ .Values.mysql.address | quote }}
      port: {{ .Values.mysql.port }}
      username: {{ .Values.mysql.username | quote }}
      password: {{ .Values.mysql.password | quote }}
      database: {{ .Values.services.user.database | quote }}  # 服务独立数据库

    rate_limiter:
      enabled: {{ .Values.services.user.rateLimiter.enabled | default false }}
      bucket_size: {{ .Values.services.user.rateLimiter.bucketSize | default 10 }}
      rate: {{ .Values.services.user.rateLimiter.rate | default 5 }}