apiVersion: v1
kind: Service
metadata:
  name: gomall-nats
  labels:
    app: gomall-nats
spec:
  type: ClusterIP
  selector:
    app: gomall-nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222