apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    app: cart
spec:
  type: ClusterIP
  selector:
    app: cart
  ports:
  - name: http
    port: 8883
    targetPort: 8883
    protocol: TCP
