apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-config
data:
  conf.yaml: |
    kitex:
      service: "checkout"
      address: ":8884"
      metrics_port: ":9994"
      log_level: info
      log_file_name: "log/kitex.log"
      log_max_size: 10
      log_max_age: 3
      log_max_backups: 50
      
    nats:
      url: "nats://gomall-nats:4222"