# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: huajuan6848/frontend:1ab2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /frontend/conf/dev
      volumes:
      - name: config
        configMap:
          name: frontend-config