# order.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
data:
  conf.yaml: |
    mysql:
      host: mysql-service
      port: 3306
    # 其他order服务配置项...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: huajuan6848/order:1ab2
        ports:
        - containerPort: 8886
        volumeMounts:
        - name: config-volume
          mountPath: /app/order/conf/dev
      volumes:
      - name: config-volume
        configMap:
          name: order-config

---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  ports:
  - protocol: TCP
    port: 8886
    targetPort: 8886