# order-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: huajuan6848/order:lab2
        ports:
        - containerPort: 8886
        volumeMounts:
        - name: config
          mountPath: /app/conf/dev
      volumes:
      - name: config
        configMap:
          name: order-config