# payment-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: huajuan6848/payment:lab2
        ports:
        - containerPort: 8887
        volumeMounts:
        - name: config
          mountPath: /app/payment/conf/dev
      volumes:
      - name: config
        configMap:
          name: payment-config