# payment.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  conf.yaml: |
    # payment服务配置项...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: huajuan6848/payment:1ab2
        ports:
        - containerPort: 8887
        volumeMounts:
        - name: config-volume
          mountPath: /app/payment/conf/dev
      volumes:
      - name: config-volume
        configMap:
          name: payment-config

---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
  ports:
  - protocol: TCP
    port: 8887
    targetPort: 8887