# product.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
data:
  conf.yaml: |
    mysql:
      host: mysql-service
      port: 3306
    # 其他product服务配置项...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: huajuan6848/product:1ab2
        ports:
        - containerPort: 8881
        volumeMounts:
        - name: config-volume
          mountPath: /app/product/conf/dev
      volumes:
      - name: config-volume
        configMap:
          name: product-config

---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  selector:
    app: product
  ports:
  - protocol: TCP
    port: 8881
    targetPort: 8881