# user.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  conf.yaml: |
    mysql:
      host: mysql-service
      port: 3306
    # 其他user服务配置项...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: huajuan6848/user:1ab2
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: config-volume
          mountPath: /app/user/conf/dev
      volumes:
      - name: config-volume
        configMap:
          name: user-config

---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888